package com.minimalisticapps.priceconverter.common.utils

data class Currency(val flag: String?)

val ALLOWED_ISO_CURRENCIES = mapOf<String, Currency>(
    "AED" to Currency(flag = null), // United Arab Emirates dirham
    "AFN" to Currency(flag = null), // Afghan afghani
    "ALL" to Currency(flag = null), // Albanian lek
    "AMD" to Currency(flag = null), // Armenian dram
    "ANG" to Currency(flag = null), // Netherlands Antillean guilder
    "AOA" to Currency(flag = null), // Angolan kwanza
    "ARS" to Currency(flag = null), // Argentine peso
    "AUD" to Currency(flag = null), // Australian dollar
    "AWG" to Currency(flag = null), // Aruban florin
    "AZN" to Currency(flag = null), // Azerbaijani manat
    "BAM" to Currency(flag = null), // Bosnia and Herzegovina convertible mark
    "BBD" to Currency(flag = null), // Barbados dollar
    "BDT" to Currency(flag = null), // Bangladeshi taka
    "BGN" to Currency(flag = null), // Bulgarian lev
    "BHD" to Currency(flag = null), // Bahraini dinar
    "BIF" to Currency(flag = null), // Burundian franc
    "BMD" to Currency(flag = null), // Bermudian dollar
    "BND" to Currency(flag = null), // Brunei dollar
    "BOB" to Currency(flag = null), // Boliviano
    "BOV" to Currency(flag = null), // Bolivian Mvdol (funds code)
    "BRL" to Currency(flag = null), // Brazilian real
    "BSD" to Currency(flag = null), // Bahamian dollar
    "BTN" to Currency(flag = null), // Bhutanese ngultrum
    "BWP" to Currency(flag = null), // Botswana pula
    "BYN" to Currency(flag = null), // Belarusian ruble
    "BZD" to Currency(flag = null), // Belize dollar
    "CAD" to Currency(flag = null), // Canadian dollar
    "CDF" to Currency(flag = null), // Congolese franc
    "CHE" to Currency(flag = null), // WIR euro (complementary currency)
    "CHF" to Currency(flag = null), // Swiss franc
    "CHW" to Currency(flag = null), // WIR franc (complementary currency)
    "CLF" to Currency(flag = null), // Unidad de Fomento (funds code)
    "CLP" to Currency(flag = null), // Chilean peso
    "COP" to Currency(flag = null), // Colombian peso
    "CRC" to Currency(flag = null), // Costa Rican colon
    "CUC" to Currency(flag = null), // Cuban convertible peso
    "CUP" to Currency(flag = null), // Cuban peso
    "CVE" to Currency(flag = null), // Cape Verdean escudo
    "CZK" to Currency(flag = null), // Czech koruna
    "DJF" to Currency(flag = null), // Djiboutian franc
    "DKK" to Currency(flag = null), // Danish krone
    "DOP" to Currency(flag = null), // Dominican peso
    "DZD" to Currency(flag = null), // Algerian dinar
    "EGP" to Currency(flag = null), // Egyptian pound
    "ERN" to Currency(flag = null), // Eritrean nakfa
    "ETB" to Currency(flag = null), // Ethiopian birr
    "EUR" to Currency(flag = null), // Euro
    "FJD" to Currency(flag = null), // Fiji dollar
    "FKP" to Currency(flag = null), // Falkland Islands pound
    "GBP" to Currency(flag = null), // Pound sterling
    "GEL" to Currency(flag = null), // Georgian lari
    "GHS" to Currency(flag = null), // Ghanaian cedi
    "GIP" to Currency(flag = null), // Gibraltar pound
    "GMD" to Currency(flag = null), // Gambian dalasi
    "GNF" to Currency(flag = null), // Guinean franc
    "GTQ" to Currency(flag = null), // Guatemalan quetzal
    "GYD" to Currency(flag = null), // Guyanese dollar
    "HKD" to Currency(flag = null), // Hong Kong dollar
    "HNL" to Currency(flag = null), // Honduran lempira
    "HRK" to Currency(flag = null), // Croatian kuna
    "HTG" to Currency(flag = null), // Haitian gourde
    "HUF" to Currency(flag = null), // Hungarian forint
    "IDR" to Currency(flag = null), // Indonesian rupiah
    "ILS" to Currency(flag = null), // Israeli new shekel
    "INR" to Currency(flag = null), // Indian rupee
    "IQD" to Currency(flag = null), // Iraqi dinar
    "IRR" to Currency(flag = null), // Iranian rial
    "ISK" to Currency(flag = null), // Icelandic króna (plural: krónur)
    "JMD" to Currency(flag = null), // Jamaican dollar
    "JOD" to Currency(flag = null), // Jordanian dinar
    "JPY" to Currency(flag = null), // Japanese yen
    "KES" to Currency(flag = null), // Kenyan shilling
    "KGS" to Currency(flag = null), // Kyrgyzstani som
    "KHR" to Currency(flag = null), // Cambodian riel
    "KMF" to Currency(flag = null), // Comoro franc
    "KPW" to Currency(flag = null), // North Korean won
    "KRW" to Currency(flag = null), // South Korean won
    "KWD" to Currency(flag = null), // Kuwaiti dinar
    "KYD" to Currency(flag = null), // Cayman Islands dollar
    "KZT" to Currency(flag = null), // Kazakhstani tenge
    "LAK" to Currency(flag = null), // Lao kip
    "LBP" to Currency(flag = null), // Lebanese pound
    "LKR" to Currency(flag = null), // Sri Lankan rupee
    "LRD" to Currency(flag = null), // Liberian dollar
    "LSL" to Currency(flag = null), // Lesotho loti
    "LYD" to Currency(flag = null), // Libyan dinar
    "MAD" to Currency(flag = null), // Moroccan dirham
    "MDL" to Currency(flag = null), // Moldovan leu
    "MGA" to Currency(flag = null), // Malagasy ariary
    "MKD" to Currency(flag = null), // Macedonian denar
    "MMK" to Currency(flag = null), // Myanmar kyat
    "MNT" to Currency(flag = null), // Mongolian tögrög
    "MOP" to Currency(flag = null), // Macanese pataca
    "MRU" to Currency(flag = null), // Mauritanian ouguiya
    "MUR" to Currency(flag = null), // Mauritian rupee
    "MVR" to Currency(flag = null), // Maldivian rufiyaa
    "MWK" to Currency(flag = null), // Malawian kwacha
    "MXN" to Currency(flag = null), // Mexican peso
    "MYR" to Currency(flag = null), // Malaysian ringgit
    "MZN" to Currency(flag = null), // Mozambican metical
    "NAD" to Currency(flag = null), // Namibian dollar
    "NGN" to Currency(flag = null), // Nigerian naira
    "NIO" to Currency(flag = null), // Nicaraguan córdoba
    "NOK" to Currency(flag = null), // Norwegian krone
    "NPR" to Currency(flag = null), // Nepalese rupee
    "NZD" to Currency(flag = null), // New Zealand dollar
    "OMR" to Currency(flag = null), // Omani rial
    "PAB" to Currency(flag = null), // Panamanian balboa
    "PEN" to Currency(flag = null), // Peruvian sol
    "PGK" to Currency(flag = null), // Papua New Guinean kina
    "PHP" to Currency(flag = null), // Philippine peso
    "PKR" to Currency(flag = null), // Pakistani rupee
    "PLN" to Currency(flag = null), // Polish złoty
    "PYG" to Currency(flag = null), // Paraguayan guaraní
    "QAR" to Currency(flag = null), // Qatari riyal
    "RON" to Currency(flag = null), // Romanian leu
    "RSD" to Currency(flag = null), // Serbian dinar
    "CNY" to Currency(flag = null), // Renminbi[14]
    "RUB" to Currency(flag = null), // Russian ruble
    "RWF" to Currency(flag = null), // Rwandan franc
    "SAR" to Currency(flag = null), // Saudi riyal
    "SBD" to Currency(flag = null), // Solomon Islands dollar
    "SCR" to Currency(flag = null), // Seychelles rupee
    "SDG" to Currency(flag = null), // Sudanese pound
    "SEK" to Currency(flag = null), // Swedish krona (plural: kronor)
    "SGD" to Currency(flag = null), // Singapore dollar
    "SHP" to Currency(flag = null), // Saint Helena pound
    "SLL" to Currency(flag = null), // Sierra Leonean leone
    "SOS" to Currency(flag = null), // Somali shilling
    "SRD" to Currency(flag = null), // Surinamese dollar
    "SSP" to Currency(flag = null), // South Sudanese pound
    "STN" to Currency(flag = null), // São Tomé and Príncipe dobra
    "SVC" to Currency(flag = null), // Salvadoran colón
    "SYP" to Currency(flag = null), // Syrian pound
    "SZL" to Currency(flag = null), // Swazi lilangeni
    "THB" to Currency(flag = null), // Thai baht
    "TJS" to Currency(flag = null), // Tajikistani somoni
    "TMT" to Currency(flag = null), // Turkmenistan manat
    "TND" to Currency(flag = null), // Tunisian dinar
    "TOP" to Currency(flag = null), // Tongan paʻanga
    "TRY" to Currency(flag = null), // Turkish lira
    "TTD" to Currency(flag = null), // Trinidad and Tobago dollar
    "TWD" to Currency(flag = null), // New Taiwan dollar
    "TZS" to Currency(flag = null), // Tanzanian shilling
    "UAH" to Currency(flag = null), // Ukrainian hryvnia
    "UGX" to Currency(flag = null), // Ugandan shilling
    "USD" to Currency(flag = null), // United States dollar
    "UYU" to Currency(flag = null), // Uruguayan peso
    "UYW" to Currency(flag = null), // Unidad previsional
    "UZS" to Currency(flag = null), // Uzbekistan som
    "VED" to Currency(flag = null), // Venezuelan bolívar digital
    "VES" to Currency(flag = null), // Venezuelan bolívar soberano
    "VND" to Currency(flag = null), // Vietnamese đồng
    "VUV" to Currency(flag = null), // Vanuatu vatu
    "WST" to Currency(flag = null), // Samoan tala
    "XAF" to Currency(flag = null), // CFA franc BEAC
    "XAG" to Currency(flag = null), // Silver (one troy ounce)
    "XAU" to Currency(flag = null), // Gold (one troy ounce)
    "XCD" to Currency(flag = null), // East Caribbean dollar
    "XOF" to Currency(flag = null), // CFA franc BCEAO
    "XPD" to Currency(flag = null), // Palladium (one troy ounce)
    "XPF" to Currency(flag = null), // CFP franc (franc Pacifique)
    "XPT" to Currency(flag = null), // Platinum (one troy ounce)
    "YER" to Currency(flag = null), // Yemeni rial
    "ZAR" to Currency(flag = null), // South African rand
    "ZMW" to Currency(flag = null), // Zambian kwacha
)
